openapi: 3.0.0
info:
  title: School Management API
  description: API for managing schools, classrooms, and user authentication.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    Unauthorized:
      description: Unauthorized access
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Unauthorized"
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Internal Server Error"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Not Found"

paths:
  /api/auth/login:
    $ref: './paths/auth.yaml#/paths/~1api~1auth~1login'

  /api/schools:
    $ref: './paths/schools.yaml#/paths/~1api~1schools'

  /api/classrooms:
    $ref: './paths/classrooms.yaml#/paths/~1api~1classrooms'

security:
  - BearerAuth: []  # Default security for all routes unless overridden
